### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing 

### ISSUE THREAD

**Issue by husky-parul** [kubernetes-sigs/cri-tools#789]
Having issues using `crictl` with `cri-o`

**Error**
```
sudo crictl info
DEBU[0000] get runtime connection                       
DEBU[0000] connect using endpoint 'unix:///var/run/crio/crio.sock' with '20s' timeout 
DEBU[0000] connected successfully using endpoint: unix:///var/run/crio/crio.sock 
DEBU[0000] StatusRequest: &StatusRequest{Verbose:true,} 
DEBU[0000] StatusResponse: nil                          
FATA[0000] getting status of runtime: rpc error: code = Unavailable desc = transport is closing 
```

`cri-o` is up and running

```
sudo systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/local/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-06-29 14:04:24 UTC; 11s ago
     Docs: https://github.com/cri-o/cri-o
 Main PID: 12914 (crio)
    Tasks: 10
   Memory: 20.2M
   CGroup: /system.slice/crio.service
           └─12914 /usr/local/bin/crio

Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.565286993Z" level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d" file="hooks/read.go:65"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.570799996Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575416259Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575534991Z" level=debug msg="Golang's threads limit set to 113670" file="server/server.go:369"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575796434Z" level=debug msg="Sandboxes: []" file="server/server.go:526"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575900517Z" level=debug msg="Registered SIGHUP watcher for config" file="config/reload.go:32"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575974287Z" level=debug msg="Metrics are disabled" file="server/server.go:537"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.578791821Z" level=error msg="remove /var/lib/crio/clean.shutdown: no such file or directory" file="crio/main.go:262"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.579959100Z" level=debug msg="monitoring \"/usr/share/containers/oci/hooks.d\" for hooks" file="hooks/monitor.go:43"
Jun 29 14:04:24 socriotel systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```

`journalctl` has no errors as well

```
journalctl -u crio.service -f
-- Logs begin at Mon 2021-06-28 18:03:41 UTC. --
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.565286993Z" level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d" file="hooks/read.go:65"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.570799996Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575416259Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575534991Z" level=debug msg="Golang's threads limit set to 113670" file="server/server.go:369"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575796434Z" level=debug msg="Sandboxes: []" file="server/server.go:526"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575900517Z" level=debug msg="Registered SIGHUP watcher for config" file="config/reload.go:32"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575974287Z" level=debug msg="Metrics are disabled" file="server/server.go:537"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.578791821Z" level=error msg="remove /var/lib/crio/clean.shutdown: no such file or directory" file="crio/main.go:262"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.579959100Z" level=debug msg="monitoring \"/usr/share/containers/oci/hooks.d\" for hooks" file="hooks/monitor.go:43"
Jun 29 14:04:24 socriotel systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```

**Steps to reproduce**
OS: centos-8
Build and install cri-o from source using [this](https://github.com/cri-o/cri-o/blob/master/install.md#fedora---rhel-7---centos)
`cri-o` is running as a `systemd` service

**Comment by saschagrunert** [comment]
Rough guess, which versions of `crio` as well as `crictl` are you using right now?

**Comment by husky-parul** [comment]
I am building cri-o from a custom branch which was based on `master` branch
For `crictl` I have tested with 1.20 and 1.21. Both versions have same issue.

**Comment by saschagrunert** [comment]
Do you get debug output from CRI-O when running `sudo crictl info`?

**Comment by husky-parul** [comment]
Do you mean `journalctl` logs? Right now I am testing it on a centos 8 VM and not on a cluster/node.
The `journalctl` doesn't have any errors (`cri-o`) is set to `debug mode`

**journalctl -u crio.service -f**
```
-- Logs begin at Mon 2021-06-28 18:03:41 UTC. --
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.565286993Z" level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d" file="hooks/read.go:65"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.570799996Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575416259Z" level=debug msg="The binary conntrack is not installed, this can cause failures in network connection cleanup.\n" file="v2/klog.go:921"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575534991Z" level=debug msg="Golang's threads limit set to 113670" file="server/server.go:369"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575796434Z" level=debug msg="Sandboxes: []" file="server/server.go:526"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575900517Z" level=debug msg="Registered SIGHUP watcher for config" file="config/reload.go:32"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.575974287Z" level=debug msg="Metrics are disabled" file="server/server.go:537"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.578791821Z" level=error msg="remove /var/lib/crio/clean.shutdown: no such file or directory" file="crio/main.go:262"
Jun 29 14:04:24 socriotel crio[12914]: time="2021-06-29 14:04:24.579959100Z" level=debug msg="monitoring \"/usr/share/containers/oci/hooks.d\" for hooks" file="hooks/monitor.go:43"
Jun 29 14:04:24 socriotel systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```

**Comment by husky-parul** [comment]
> Do you get debug output from CRI-O when running `sudo crictl info`?

```
sudo crictl info
DEBU[0000] get runtime connection                       
DEBU[0000] connect using endpoint 'unix:///var/run/crio/crio.sock' with '20s' timeout 
DEBU[0000] connected successfully using endpoint: unix:///var/run/crio/crio.sock 
DEBU[0000] StatusRequest: &StatusRequest{Verbose:true,} 
DEBU[0000] StatusResponse: nil                          
FATA[0000] getting status of runtime: rpc error: code = Unavailable desc = transport is closing 
```

**Comment by saschagrunert** [comment]
That's really strange, what is the output of:
```
> sudo GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info crictl version
```

**Comment by husky-parul** [comment]
> That's really strange, what is the output of:
> 
> ```
> > sudo GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info crictl version
> ```

```
sudo GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info crictl version
INFO: 2021/07/15 15:40:29 [core] parsed scheme: ""
INFO: 2021/07/15 15:40:29 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/07/15 15:40:29 [core] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/07/15 15:40:29 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/07/15 15:40:29 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/07/15 15:40:29 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/07/15 15:40:29 [core] Subchannel picks a new address "/var/run/crio/crio.sock" to connect
INFO: 2021/07/15 15:40:29 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004b4e70, {CONNECTING <nil>}
INFO: 2021/07/15 15:40:29 [core] Channel Connectivity change to CONNECTING
INFO: 2021/07/15 15:40:29 [core] Subchannel Connectivity change to READY
INFO: 2021/07/15 15:40:29 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004b4e70, {READY <nil>}
INFO: 2021/07/15 15:40:29 [core] Channel Connectivity change to READY
INFO: 2021/07/15 15:40:29 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/07/15 15:40:29 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/07/15 15:40:29 [core] Subchannel Connectivity change to SHUTDOWN
FATA[0000] getting the runtime version: rpc error: code = Unavailable desc = transport is closing 
```
@saschagrunert

**Comment by husky-parul** [comment]
Env Centos-8
`cri-o` https://github.com/sallyom/cri-o/tree/otel-trace-2
`conmon` https://github.com/haircommander/conmon/tree/seccomp-notify-make-fix
`crictl` v1.21.0

**Comment by saschagrunert** [comment]
@husky-parul CRI-O seems to crash with https://github.com/sallyom/cri-o/tree/otel-trace-2:

```
DEBU[2021-07-16 09:59:35.147539827+02:00] Request: &VersionRequest{Version:v1alpha2,}   file="go-grpc-middleware/chain.go:25" id=7d9d086d-bbc4-4976-8843-a52677b51dc3 name=/runtime.v1alpha2.RuntimeService/Version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d4ec6d]

goroutine 118 [running]:
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2527660, 0xc0009a58c0, 0x20f4dc0, 0xc00000f230, 0xc000349950, 0x1, 0x1, 0xa)
        /home/sascha/downloads/cri-o/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x2d
github.com/cri-o/cri-o/internal/log.UnaryInterceptor.func1(0x2527660, 0xc0009a45a0, 0x20f4dc0, 0xc00000f230, 0xc0005b02a0, 0xc0005b02c0, 0x4e30c6, 0x60f13c67, 0x8ca424f, 0x31575f7832f)
        /home/sascha/downloads/cri-o/internal/log/interceptors.go:56 +0x116
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2527660, 0xc0009a45a0, 0x20f4dc0, 0xc00000f230, 0xc0005b0300, 0x20, 0x20, 0x2034420)
        /home/sascha/downloads/cri-o/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63
github.com/cri-o/cri-o/server/metrics.UnaryInterceptor.func1(0x2527660, 0xc0009a45a0, 0x20f4dc0, 0xc00000f230, 0xc0005b02a0, 0xc0005b02e0, 0x1d4ed3a, 0x2034420, 0xc0005b0300, 0xc0005b02a0)
        /home/sascha/downloads/cri-o/server/metrics/interceptors.go:24 +0xc6
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2527660, 0xc0009a45a0, 0x20f4dc0, 0xc00000f230, 0xc000184400, 0x0, 0xc000349b30, 0x41bb98)
        /home/sascha/downloads/cri-o/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x2527660, 0xc0009a45a0, 0x20f4dc0, 0xc00000f230, 0xc0005b02a0, 0xc0009244f8, 0xc000177ba0, 0x52c6a6, 0x207c7a0, 0xc0009a45a0)
        /home/sascha/downloads/cri-o/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0xd7
k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_Version_Handler(0x21862c0, 0xc00059c178, 0x2527660, 0xc0009a45a0, 0xc0004d84e0, 0xc000866240, 0x2527660, 0xc0009a45a0, 0xc00051a290, 0xa)
        /home/sascha/downloads/cri-o/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go:7878 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000506e00, 0x2540cd8, 0xc000622c00, 0xc0006545a0, 0xc00059a810, 0x3301ac0, 0x0, 0x0, 0x0)
        /home/sascha/downloads/cri-o/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000506e00, 0x2540cd8, 0xc000622c00, 0xc0006545a0, 0x0)
        /home/sascha/downloads/cri-o/vendor/google.golang.org/grpc/server.go:1617 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00051a200, 0xc000506e00, 0x2540cd8, 0xc000622c00, 0xc0006545a0)
        /home/sascha/downloads/cri-o/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/sascha/downloads/cri-o/vendor/google.golang.org/grpc/server.go:938 +0x1fd
```
